<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PartnerSchools; // Update this to your actual Model school_namespace

class PartnerSchoolsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $schools = [
            [
                'school_name' => 'ACLC - Batangas City',
                'abbreviation' => 'ACLC',
                'contact_first_name' => null,
                'contact_last_name' => null,
                'contact_email' => 'http://www.aclc.edu.ph/p/aclc-college-batangas.html', // Kept as provided, though it looks like a URL
                'physical_address' => 'Batangas City',
                'status' => 'active',
            ],
            [
                'school_name' => 'ACLC - San Pablo City',
                'abbreviation' => 'ACLC - SPC',
                'contact_first_name' => null,
                'contact_last_name' => null,
                'contact_email' => 'aclc_sanpablo@amaes.edu.ph',
                'physical_address' => 'Barangay, Inocencio Barleta St, San Pablo City, Laguna',
                'status' => 'active',
            ],
            [
                'school_name' => 'Batangas State University - Alangilan (Main)',
                'abbreviation' => 'BSU - Alangilan',
                'contact_first_name' => null,
                'contact_last_name' => null,
                'contact_email' => 'batstate-u.edu.ph',
                'physical_address' => 'Urban; Main campus: Rizal Ave, Batangas City',
                'status' => 'active',
            ],
            [
                'school_name' => 'Batangas State University - Lipa',
                'abbreviation' => 'BSU - Lipa',
                'contact_first_name' => null,
                'contact_last_name' => null,
                'contact_email' => 'batstate-u.edu.ph',
                'physical_address' => 'A. Tanco Drive, Maraouy, Lipa, Batangas',
                'status' => 'active',
            ],
            [
                'school_name' => 'Bicol University Polangui',
                'abbreviation' => 'BU',
                'contact_first_name' => null,
                'contact_last_name' => null,
                'contact_email' => null,
                'physical_address' => 'Polangui, Albay',
                'status' => 'active',
            ],
            [
                'school_name' => 'Cavite State University',
                'abbreviation' => 'CvSU',
                'contact_first_name' => null,
                'contact_last_name' => null,
                'contact_email' => 'https://cvsu.edu.ph/',
                'physical_address' => 'Indang, Cavite, Philippines',
                'status' => 'active',
            ],
            [
                'school_name' => 'Cavite State University - Cavite',
                'abbreviation' => 'CvSU - Cavite',
                'contact_first_name' => null,
                'contact_last_name' => null,
                'contact_email' => null,
                'physical_address' => 'FV5J+C37, Dalahican, Cavite City, 4100 Cavite',
                'status' => 'active',
            ],
            [
                'school_name' => 'Cavite State University - Rosario',
                'abbreviation' => 'CvSU - Rosario',
                'contact_first_name' => null,
                'contact_last_name' => null,
                'contact_email' => 'office.president@cvsu.edu.ph',
                'physical_address' => 'CV38+C99, Rosario, Cavite',
                'status' => 'active',
            ],
            [
                'school_name' => 'Colegio de San Juan de Letran - Calamba',
                'abbreviation' => 'CSJL - Calamba',
                'contact_first_name' => null,
                'contact_last_name' => null,
                'contact_email' => 'letran-calamba.edu.ph',
                'physical_address' => '55Q8+F5J, Bucal Bypass Rd, Calamba, 4027 Laguna',
                'status' => 'active',
            ],
            [
                'school_name' => 'De La Salle University - Lipa',
                'abbreviation' => 'DLSU - Lipa',
                'contact_first_name' => 'Emilio Manuel ',
                'contact_last_name' => 'Macaso (ITE)',
                'contact_email' => 'helpdesk@dlsl.edu.ph',
                'physical_address' => '1962 J.P. Laurel National Highway, Mataas na Lupa, 4217, Batangas',
                'status' => 'active',
            ],
            [
                'school_name' => 'Greenville Academy of Sta. Clara',
                'abbreviation' => 'GVA',
                'contact_first_name' => 'Cindy',
                'contact_last_name' => 'Malabuyo',
                'contact_email' => 'https://www.facebook.com/greenville2000/',
                'physical_address' => '26H3+8F9, Santo Tomas, Batangas',
                'status' => 'active',
            ],
            [
                'school_name' => 'Laguna College',
                'abbreviation' => 'LC',
                'contact_first_name' => null,
                'contact_last_name' => null,
                'contact_email' => 'registrar.laguna.college@gmail.com',
                'physical_address' => 'Paseo de Escudero at Zulueta ST, Paseo de Escudero, Lungsod ng San Pablo, 4000 Laguna',
                'status' => 'active',
            ],
            [
                'school_name' => 'Laguna State Polytechnic University - Los Baños Campus',
                'abbreviation' => 'LSPU - Los Baños Cam',
                'contact_first_name' => null,
                'contact_last_name' => null,
                'contact_email' => null,
                'physical_address' => 'Los Baños, 4030 Laguna',
                'status' => 'active',
            ],
            [
                'school_name' => 'Laguna State Polytechnic University - San Pablo City Campus',
                'abbreviation' => 'LSPU - SPCC',
                'contact_first_name' => 'Mr. Ronnel',
                'contact_last_name' => 'Dela Cruz',
                'contact_email' => 'lspu@lspu.edu.ph',
                'physical_address' => '38M6+6VQ, Cosico Ave, San Pablo City, 4000 Laguna',
                'status' => 'active',
            ],
            [
                'school_name' => 'Laguna State Polytechnic University - Santa Cruz (Main) Campus',
                'abbreviation' => 'LSPU - SCC',
                'contact_first_name' => null,
                'contact_last_name' => null,
                'contact_email' => null,
                'physical_address' => 'Santa Cruz, Laguna',
                'status' => 'active',
            ],
            [
                'school_name' => 'Lyceum Polytechnic University - Batangas',
                'abbreviation' => 'LPU - Batangas',
                'contact_first_name' => null,
                'contact_last_name' => null,
                'contact_email' => 'inquiry@lpubatangas.edu.ph',
                'physical_address' => 'P. Herera street corner Dona Aurelia street, Batangas, 4200 Batangas',
                'status' => 'active',
            ],
            [
                'school_name' => 'Marcelino Fule Memorial College',
                'abbreviation' => 'MFMC',
                'contact_first_name' => 'Harold Alea',
                'contact_last_name' => 'Coronado',
                'contact_email' => 'mfmcollege1946@yahoo.com',
                'physical_address' => 'Del Pilar Street, 1, Alaminos, Laguna',
                'status' => 'active',
            ],
            [
                'school_name' => 'National University (Laguna)',
                'abbreviation' => 'NU',
                'contact_first_name' => 'Noreen Clarice',
                'contact_last_name' => 'Borda',
                'contact_email' => 'naborda@nu-laguna.edu.ph',
                'physical_address' => 'KM 53 Pan-Philippine Hwy, Calamba, 4027 Laguna',
                'status' => 'active',
            ],
            [
                'school_name' => 'Others',
                'abbreviation' => 'Others',
                'contact_first_name' => '',
                'contact_last_name' => '',
                'contact_email' => 'Others@gmail.com',
                'physical_address' => 'Others',
                'status' => 'active',
            ],
            [
                'school_name' => 'Pamantasan ng Lungsod ng San Pablo',
                'abbreviation' => 'PLSP',
                'contact_first_name' => null,
                'contact_last_name' => null,
                'contact_email' => 'n/a@gmail.com', // Kept as provided
                'physical_address' => '387R+JMP, Alvarez St., San Pablo City, Laguna',
                'status' => 'active',
            ],
            [
                'school_name' => 'Polytechnic University of the Philippines - Lopez',
                'abbreviation' => 'PUP - Lopez',
                'contact_first_name' => null,
                'contact_last_name' => null,
                'contact_email' => 'inquire@pup.edu.ph',
                'physical_address' => '4316, Lopez, 4316 Quezon',
                'status' => 'active',
            ],
            [
                'school_name' => 'San Pablo Colleges',
                'abbreviation' => 'SPC',
                'contact_first_name' => 'Chelsea',
                'contact_last_name' => 'Lim',
                'contact_email' => 'sanpablocolleges.edu.ph',
                'physical_address' => '3a Hermanos Belen Street, San Pablo City, 4000 Laguna',
                'status' => 'active',
            ],
            [
                'school_name' => 'Servite Catholic School Laurel Batangas',
                'abbreviation' => 'SCSLB',
                'contact_first_name' => 'Mr. Joshua',
                'contact_last_name' => 'Magsino',
                'contact_email' => 'servitecatholicschool99@gmail.com',
                'physical_address' => 'Laurel Batangas',
                'status' => 'active',
            ],
            [
                'school_name' => 'Southern Luzon State University',
                'abbreviation' => 'SLSU',
                'contact_first_name' => null,
                'contact_last_name' => null,
                'contact_email' => 'slsuregistrar@slsu.edu',
                'physical_address' => 'Lucban - Tayabas Rd, Lucban, 4328 Quezon',
                'status' => 'active',
            ],
            [
                'school_name' => 'St. Nicolas Golden Field Academy Inc',
                'abbreviation' => 'SNGFAI',
                'contact_first_name' => null,
                'contact_last_name' => null,
                'contact_email' => 'sngfai.spc@gmail.com',
                'physical_address' => 'Maharlika Highway, Brgy. San Nicolas, San Pablo City, Philippines, 4000',
                'status' => 'active',
            ],
            [
                'school_name' => 'St. Therese Montessori School of San Pablo, Inc.',
                'abbreviation' => 'STMS',
                'contact_first_name' => 'Lara Jane',
                'contact_last_name' => 'Yedra',
                'contact_email' => 'st_theresemontessori_spc@yahoo.com',
                'physical_address' => 'Brgy. San Nicolas, San Pablo City',
                'status' => 'active',
            ],
            [
                'school_name' => 'STI College San Pablo',
                'abbreviation' => 'STI SPC',
                'contact_first_name' => 'Angelou',
                'contact_last_name' => 'Almare-Medina',
                'contact_email' => 'sti.edu',
                'physical_address' => '4000 Lopez Jaena St, San Pablo City, Laguna',
                'status' => 'active',
            ],
            [
                'school_name' => 'Technological Institute of the Philippines - Manila',
                'abbreviation' => 'TIP - Manila',
                'contact_first_name' => null,
                'contact_last_name' => null,
                'contact_email' => 'info@tip.edu.ph',
                'physical_address' => '363 Casal St, Quiapo, Manila, 1001 Metro Manila',
                'status' => 'active',
            ],
            [
                'school_name' => 'Teodoro Luansing College of Rosario',
                'abbreviation' => 'TLCR',
                'contact_first_name' => null,
                'contact_last_name' => null,
                'contact_email' => 'www.facebook.com/TMLCR2004Official',
                'physical_address' => 'R6V2+R3X, Ibaan Road, Rosario, Batangas',
                'status' => 'active',
            ],
            [
                'school_name' => 'University of Batangas',
                'abbreviation' => 'UB',
                'contact_first_name' => 'Reydexter',
                'contact_last_name' => 'Abutar',
                'contact_email' => 'admin@ub.edu.ph',
                'physical_address' => 'Kumintang Ibaba, Batangas City, Philippines',
                'status' => 'active',
            ],
            [
                'school_name' => 'University of Batangas - Lipa',
                'abbreviation' => 'UB - Lipa',
                'contact_first_name' => 'Jennifer',
                'contact_last_name' => 'Pasahol',
                'contact_email' => 'jennifer.pasahol@ub.edu.ph',
                'physical_address' => 'Leviste Hwy, Lipa, Batangas',
                'status' => 'active',
            ],
        ];

        foreach ($schools as $school) {
            PartnerSchools::updateOrCreate(
                ['school_name' => $school['school_name']], // Unique identifier to check existence
                $school
            );
        }
    }
}
