# OPTIMIZED LARAVEL OCTANE (FRANKENPHP) + INERTIA SSR CONFIG

[phases.setup]
pkgs = ["php", "composer", "nodejs", "npm"]

[phases.install]
cmds = [
  "composer install --no-interaction --prefer-dist --no-dev --optimize-autoloader",
  "npm ci",
  "php artisan octane:install --server=frankenphp --no-interaction"
]

[phases.build]
cmds = [
  "npm run build",
  "chmod +x frankenphp"
]

[start]
cmd = "bash scripts/deploy.sh"